[Advanced settings for MoA]
; Use an LLM to select artists instead of a simple keyword search (true or false):
MoAAI=true
; Use this port for MoA (if LLM mode is enabled):
MoAPort=64102
; This model determines which artist to use:
MoAModel=https://huggingface.co/unsloth/gemma-3-4b-it-GGUF/resolve/main/gemma-3-4b-it-Q8_0.gguf
; Load the MoA model to the GPU for faster selection (true or false):
MoAGPU=true
