[Advanced settings for chat]
; Use this port for chat:
LlamaCppPort=64100
; Allow local network to reach the chat's native webpage (true or false):
ChatLocalhost=false
; If chat replies are not done in this many seconds, cancel the generation:
ChatTimeout=90
; When switching models, allow this many extra seconds over the normal timeout:
ChatLoading=15
; Randomness of generated answers. 0 = strict, larger numbers are more creative:
ChatTemperature=0.8
; Minimum probability for token selection:
ChatMinP=0.05
; Presence penalty to reduce repetition of tokens already in context:
ChatPresencePenalty=0
; Maximum number of tokens to generate (-1 = infinite):
ChatPredict=-1
; Maximum context length for prompts when small models are in use:
ChatContextSLM=4096
; Maximum context length for prompts when large models are in use:
ChatContextLLM=16384
; Number of tokens to maximally use for a single reasoning session:
ChatReasoningBudget=1536
; How much to keep of the initial prompt context for each generation:
ChatKeep=128
; How much space to keep at the end of the context window for new messages:
ChatDiscard=512
; When using models with Multi-Token Prediction, predict this many at once:
ChatMTP=1
; Parallel requests chat can serve, larger values take up more RAM:
ChatParallel=1
; Apply PMAI-supplied fixes to some known wrong LLM templates:
ChatFixes=true
; Comma-separated list of API keys if you want to provide them:
ChatApiKeys=

; Folder of extra knowledge for the chat (readme tells you how to add these):
ContextDocTree=Context Doc Tree
; Load all loosely matching context docs (requires large context windows):
FullContext=true
; Only search context docs for the latest prompt (huge performance gain):
AugmentLatestOnly=false
; Also add the system prompt to each augmentation evaluation. One good use case is
; adding a trigger word for a folder and limiting augmentation that way to a
; single model.
AugmentWithSystemPrompt=false
