[Advanced settings for image generation]
; Use this port for image generation:
WebUIPort=64101
; If images are not done in this many seconds, cancel the generation:
ImageGenTimeout=60
; When switching models, allow this many extra seconds over the normal timeout:
ImageGenLoading=15
; When a reference image is used, allow this many extra seconds of timeout:
ImageGenParsing=2
; Number of times the image is refined for better results:
ImageGenSteps=4
; How close the prompts are followed, read your models' recommendation:
ImageGenGuidance=1.5
; Sampler method used for image generation, read your models' recommendation:
ImageGenSampler=DPM++ SDE
