[Advanced settings for agents]
; Enable sending email notifications from the agent:
AgentSendEmail=false
; SMTP server address:
AgentEmailServer=
; SMTP port (587 for TLS, 465 for SSL, 25 for unencrypted):
AgentSMTPPort=587
; SMTP use STARTTLS (true) or SSL (false):
AgentSMTPStartTLS=true
; Email account username:
AgentEmailUser=
; Email account password:
AgentEmailPassword=
; Email recipient for agent completion notifications:
AgentEmailRecipient=
; If set, only allow this comma-separated list of path beginnings:
AgentFolderWhitelist=
; Remove disabled tools lines from agent output (true/false):
AgentSanitization=true
; How GitHub Copilot (if used as agent) will display the model:
Agent1CopilotModel=Poor Man's AI
; GitHub Copilot (if used as agent) shall not connect to GitHub at all:
Agent1CopilotOffline=true
; Where your chat model is ran at if GitHub Copilot is used as agent:
Agent1CopilotProviderBaseUrl=http://localhost:64100/v1
; Maximum input/output tokens for the agent model:
Agent1CopilotMaxTokens=4096

; Same settings for other agents:
Agent2=OpenRouter
Agent2CopilotModel=poolside/laguna-s-2.1:free
Agent2CopilotOffline=false
Agent2CopilotProviderBaseUrl=https://openrouter.ai/api/v1
Agent2CopilotProviderApiKey=YOUR_KEY_HERE
