[Folders]
; All folders can be any path, including absolute paths.
; Where llama.cpp's CPU version is unpacked to:
LlamaCppCPURoot=llama.cpp AVX2
; Where llama.cpp's GPU version is unpacked to:
LlamaCppGPURoot=llama.cpp CUDA
; The folder where Large Language Models (LLMs) are saved:
Models=Chat models
; Where AUTOMATIC1111's Stable Diffusion WebUI is unpacked to:
WebUIRoot=Stable Diffusion WebUI
; Put artists to this folder (can be any path, even absolute):
Artists=Artists
; Put negative embeddings to this folder (can be any path, even absolute):
Embeddings=Embeddings
